# Generated by Django 2.0 on 2017-12-04 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('readOnly', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'System'), (1, 'Binary Output'), (2, 'Integer Output'), (3, 'Binary Input'), (4, 'Decimal Input'), (5, 'Integer Input'), (6, 'String'), (7, '¡Reserved!'), (8, 'Error')])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idona.Device')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('id', 'device')},
        ),
    ]
