# Generated by Django 2.0 on 2017-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='binaryValue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='decimalValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='integerValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='stringValue',
            field=models.CharField(default='', max_length=256),
        ),
    ]
