# Generated by Django 2.0 on 2017-12-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idona', '0002_auto_20171208_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputMatrix', to='idona.Endpoint')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputMatrix', to='idona.Endpoint')),
            ],
        ),
    ]
