# Generated by Django 2.0 on 2017-12-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idona', '0002_auto_20171208_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputs', models.ManyToManyField(related_name='outputMatrix', to='idona.Endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='inputMatrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='idona.EndpointMatrix'),
        ),
    ]
