# Generated by Django 2.0 on 2017-12-11 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idona', '0003_endpointmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmatrix',
            name='fromTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='endpointmatrix',
            name='toTime',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999)),
        ),
    ]
