# Generated by Django 2.0 on 2017-12-12 16:02

from django.db import migrations
import weekday_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('idona', '0004_auto_20171211_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmatrix',
            name='days',
            field=weekday_field.fields.WeekdayField(default=[0, 1, 2, 3, 4, 5, 6], max_length=14),
        ),
    ]
